graphql-hive/graphql-modules

packages/logger/package.json
Moment doesn't appear to be used for anything
=> chore: Remove moment

README.md
👋
Shell uses `#` instead of `//` to do comments. Also added a code block with language notes.
=> Update shell comments

packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts
=> WIP: __resolveType not getting `injector`

packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts
Add `schemaDirectives` option to support directivevisitors in graphql-modules.
=> Add schema directives support

packages/core/src/di/injectable.ts, packages/core/src/di/injector.ts, packages/core/src/di/types.ts, packages/core/src/errors/dependency-provider-not-found.ts, packages/core/src/errors/index.ts, packages/core/src/errors/provider-already-defined.ts, packages/core/src/errors/provider-not-valid.ts, packages/core/src/errors/schema-not-valid.ts, packages/core/src/errors/service-identifier-not-found.ts, packages/core/src/graphql-module.ts, packages/core/src/utils.ts, packages/core/tests/graphql-module.spec.ts
=> Enhance errors and introduce providedIn

packages/core/src/graphql-module.ts, packages/epoxy/src/schema-mergers/merge-schema.ts, packages/epoxy/tests/merge-schema.spec.ts
Expose typeDefs as DocumentNode instead of string
=> Expose typeDefs as DocumentNode

packages/epoxy/src/schema-mergers/merge-schema.ts, packages/epoxy/src/schema-mergers/utils.ts, packages/epoxy/tests/merge-schema.spec.ts
=> Should accept root schema object

packages/epoxy/src/schema-mergers/merge-schema.ts, packages/epoxy/tests/merge-schema.spec.ts
@ardatan this would fix: https://github.com/accounts-js/accounts/issues/499#issuecomment-441635435
=> UseSchemaDefinition option in mergeGraphQLSchemas

packages/epoxy/src/schema-mergers/merge-schema.ts, packages/epoxy/tests/merge-schema.spec.ts
This causes an issue in ✈️ project.
@ardatan Could you review it and publish?
=> Epoxy omits scalars

packages/epoxy/src/schema-mergers/merge-schema.ts
=> Don't overwrite query definition with subscription

packages/core/src/errors/context-builder.ts, packages/core/src/errors/index.ts, packages/core/src/graphql-module.ts
=> Better internal error handling for context builders

docs/introduction/integrate-with-dataloaders.md
=> Add docs for DataLoaders

docs/introduction/modules.md
Fixes a few grammatical errors, fixes syntax tabbing in code blocks, and a little rewording for clarity.
=> chore(docs): update docs/introduction/modules.md

packages/core/src/graphql-module.ts
=> Do not search for subscribe method if it is not an object

docs/introduction/test-your-module.md, packages/di/src/injector.ts, packages/di/tests/di.spec.ts, packages/di/tests/tsconfig.json
=> Fix overwriting providers

docs/introduction/dependency-injection.md, docs/introduction/subscriptions.md, packages/core/src/graphql-module.ts, packages/core/src/types.ts
=> onOperation and onOperationComplete hooks

packages/core/src/graphql-module.ts
=> Pass correct session to context builder for subscriptions

packages/core/src/graphql-module.ts
=> Fix onOperation and onOperationComplete hooks

docs/recipes/data-loader.md
=> Mention per-request caching in dataloaders docs

docs/recipes/development-environment.md
add an example to explain how to using decorators
=> Improve decorators doc

docs/recipes/development-environment.md
Improve Js Inject without decorator
=> Improve Inject JS

packages/di/src/injector.ts
=> Throw if error is not related to service identifier

docs/recipes/apollo-server.md, examples/apollo-modules/package.json, examples/apollo-modules/src/app/app.module.ts, examples/apollo-modules/src/app/auth/auth.module.ts, examples/apollo-modules/src/app/social-network/social-network.module.ts, examples/apollo-modules/src/app/user/user.module.ts, examples/apollo-modules/src/index.ts, examples/apollo-modules/tsconfig.json, examples/subscriptions/package.json, examples/subscriptions/src/app/app.module.ts, examples/subscriptions/src/app/common/common.module.ts, examples/subscriptions/src/app/post/post.module.ts, examples/subscriptions/src/app/post/post.provider.ts, examples/subscriptions/src/index.ts, examples/subscriptions/tsconfig.json, packages/core/package.json, packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts, yarn.lock
- Fix resolver types and add example for apollo-server
- Wait for https://github.com/ardatan/graphql-toolkit/pull/133
- Related to #427
=> Fix resolver types

packages/core/src/graphql-module.ts
=> Fix context mocking

packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts
=> Able to inject ModuleConfig without module itself

packages/core/src/graphql-module.ts, packages/core/src/types.ts
=> Make resolvers optional (type)

packages/di/src/injector.ts
=> Fix priority of scopes in useClass

packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts
=> Support isTypeOf

packages/core/tests/graphql-module.spec.ts, packages/di/src/errors/dependency-provider-not-found.ts, packages/di/src/errors/service-identifier-not-found.ts, packages/di/src/injector.ts
=> Show user more details of DI errors

docs/introduction/configuration.md, docs/introduction/context.md, docs/introduction/dependencies.md, docs/introduction/dependency-injection.md, docs/introduction/getting-started.md, docs/introduction/implement-providers.md, docs/introduction/implement-resolvers.md, docs/introduction/implement-server.md, docs/introduction/modules.md, docs/introduction/resolvers-composition.md, docs/introduction/subscriptions.md, docs/introduction/test-your-module.md, docs/introduction/understanding-session.md, docs/introduction/your-first-module.md
The documents of GraphQL Modules are very helpful, but some parts were a bit hard for me to understand.
I amended docs/introduction. I fixed typos and punctuations, formatted the snippets in a consistent way, and altered some phrasing. I hope that these changes are acceptable.
=> Amend docs/introduction

packages/core/src/graphql-module.ts, packages/core/tests/graphql-module.spec.ts
=> Fixed schemaAsync modules schema merging

packages/core/src/graphql-module.ts
As discussed at #850, add more logger method and change log method interface
=> Add more logger interface

packages/core/src/graphql-module.ts, packages/tools/cli/src/commands/utils.ts
use boolean instead of filter(val => val) check
=> use boolean shortcut for filters

docs/introduction/dependency-injection.md, packages/core/src/types.ts
Will allow onError to function in TS environment. Small doco correction.
Cheers.
=> Correct onError type and doc

examples/basic-with-dependency-injection/package-lock.json, examples/basic-with-dependency-injection/package.json, examples/basic-with-dependency-injection/src/index.ts, examples/basic-with-dependency-injection/src/modules/app/app.module.ts, examples/basic-with-dependency-injection/src/modules/blog/index.ts, examples/basic-with-dependency-injection/tsconfig.json
* Install missing dependency -- graphql-tag
* Fix importing module in index.ts and enhance it a little
=> Fix Example(basic-with-dependency-injection)

docs/recipes/type-graphql.md
* Use correct URL (they switched to a .com domain)
* Add hint for correct setup in order to use type-graphl
=> Update type-graphql.md (#1085) [deploy_website]

docs/introduction/context.md
Would help those coming from vanilla graphql.
=> Explain clearly that modules are isolated

examples/basic-with-dependency-injection/package.json
=> Add tsconfig-paths to deps

website/docs/advanced/execution-context.md
=> fix: docs link

packages/graphql-modules/src/application/application.ts, packages/graphql-modules/src/shared/utils.ts, packages/graphql-modules/tests/providers.spec.ts
=> test: operation scoped provider should be created once per GraphQL Operation

packages/graphql-modules/tests/providers.spec.ts
=> Missing providers list on module gives error

packages/graphql-modules/src/application/application.ts, packages/graphql-modules/tests/context.spec.ts, packages/graphql-modules/tests/providers.spec.ts
=> Fix global and module context

packages/graphql-modules/tests/providers.spec.ts
=> reproduce provider error

.changeset/curly-bananas-hang.md
Related: https://github.com/Urigo/graphql-modules/pull/1344
=> Added missing changeset for PR 1344

examples/basic-with-dependency-injection-js/src/index.js, examples/basic-with-dependency-injection/src/index.ts, examples/basic/src/index.ts
Follow up module：express-graphql
=> fix(examples): use express-graphql 'graphqlHTTP'

.changeset/two-taxis-bake.md, jest.config.base.js, packages/graphql-modules/src/module/metadata.ts, packages/graphql-modules/tests/bootstrap.spec.ts, patches/@changesets+apply-release-plan+4.1.0.patch
Related: https://github.com/Urigo/graphql-modules/issues/1459
=> Fix for multiple extensions

website/docs/get-started.md
just to make clear where functions come from
=> fix: helix example

.changeset/yellow-news-roll.md, packages/graphql-modules/src/module/metadata.ts, packages/graphql-modules/src/module/resolvers.ts
For issue addressed in https://github.com/Urigo/graphql-modules/issues/1522
=> Support __resolveReference resolver for federation

.github/workflows/website.yml, algolia/config.json, website/docusaurus.config.js, website/patches/@docsearch+react+1.0.0-alpha.28.patch
Related to https://github.com/the-guild-org/the-guild-website/issues/300
Adds support for multi-site search to `graphql-modules` website
=> Added support for Multi-site search

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
This PR is related to https://github.com/the-guild-org/Stack/pull/9
- Added PR and issue templates
- Updated README with CODE OF CONDUCT, Contributions and LICENSE
=> Added PR and issue templates, Updated README with contributing, code of conduct and license

packages/graphql-modules/src/di/decorators.ts
=> Fix race condition between Inject and Injectable

.changeset/young-cats-live.md, .github/workflows/benchmark.yml, .github/workflows/canary.yml, .github/workflows/ci.yml, .github/workflows/release.yml, benchmark/basic.case.ts, packages/graphql-modules/src/application/apollo.ts, packages/graphql-modules/src/application/application.ts, packages/graphql-modules/src/application/context.ts, packages/graphql-modules/src/shared/utils.ts, packages/graphql-modules/tests/third-parties.spec.ts
=> Fix cache control

website/docusaurus.config.js, website/package.json, website/src/css/custom.css
Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components
=> [deploy_website] Algolia Config Removal

packages/graphql-modules/src/module/resolvers.ts
We use `__resolveObject` extensively in our codebase. Looking at the of `graphql-modules` it looks like it assumes the wrong signature of the (somewhat poorly documented resolver function).
The code assumes the signature is the same as `__resolveReference`, i.e.
```
__resolveObject(root, context, info)
```
(see `src/modules/resolvers.ts`) 
while the signature is in fact
```
__resolveObject(root, fields, context, info)
```
This PR provides a fix to use the correct signature
Fixes #1663
=> Use correct __resolveObject signature

website/docs/api.md, website/docusaurus.config.js, website/package.json, website/src/theme/Root.js
- components no longer rendered using `<BrowserOnly />`
- included TGC `<GlobalStyles />` for correct font styling
- included TGC `<FooterExtended />`
=> [deploy_website]  TGC Fixes

website/docs/index.md
Fix grammar and syntax issues in modules docs.
=> Fix grammar and syntax issues in modules docs.

.changeset/rare-apples-fly.md, package.json, packages/graphql-modules/src/testing/test-module.ts, packages/graphql-modules/tests/di-providers.spec.ts, packages/graphql-modules/tests/testing.spec.ts, yarn.lock
=> Allow to overwrite providers when using testkit.testModule

.github/workflows/algolia-integrity.yml, .github/workflows/algolia-publish.yml, .github/workflows/benchmark.yml, .github/workflows/tests.yml, package.json
- OS:
- `@graphql-modules/...`:
- …
=> ci: refactor to use guild composite actions

website/src/pages/docs/get-started.mdx
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
**Test …
=> Website docs: Fix broken links - Error 404

website/src/index-page.tsx
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
**Test …
=> Ahrefs warning: `alt` missing

website/src/pages/docs/di/providers.mdx
=> docs: typo fix

website/src/pages/docs/essentials/context.mdx
- OS:
- `@graphql-modules/...`:
- …
=> Fix 404 pages error

website/src/pages/docs/get-started.mdx
I went to https://the-guild.dev/graphql/yoga-server/docs to find the latest steps. Not sure if this is correct but it worked for me.
=> Fix GraphQL Yoga docs example
