- docs/guides/development-environment.md
- packages/core/src/di/injector.ts
- packages/core/src/graphql-module.ts
- packages/core/tsconfig.json
- Use Set to prevent duplications before merging schema
- Use deepmerge instead of `reduce` for merging array of objects
> Speed improvements

- packages/core/src/graphql-module.ts
Now module object is also passed to the factory function
```ts
somefield: (config: Config, module: GraphQLModule) => ...
```
So, independent fields can be used inside of factory function.
```ts
resolversComposition: (config, { typeDefs }) => {
}
```
> Expose module itself together with factories

- packages/epoxy/src/schema-mergers/merge-schema.ts
- packages/epoxy/tests/merge-schema.spec.ts
Instead of using `printSchema`, we are using now `print` per each type in the schema, and the same for the directives. `print` preserves directives, while `printSchema` uses introspection and removes it.
> Fix directive merging for GraphQLSchema objects

- examples/basic-with-dependency-injection/package.json
`basic-with-dependency-injection` example is lack of `@graphql-modules/di` dependency which is required by both of `User` and `Blog` providers.
> Add missing dependency @graphql-modules/di to the examples

- packages/core/tests/graphql-module.spec.ts
- packages/di/src/inject.ts
- packages/di/src/injectable.ts
- packages/di/src/injector.ts
- packages/di/src/utils.ts
Now you can use `Inject` in a property without defining constructor.
```
@Injectable()
class FooProvider {
@Inject()
barProvider: BarProvider
}
```
BUT due to some typings conflicts, I seperated `Inject` decorator and wrappers, so factory functions should be wrapped with `InjectFunction` not `Inject`.
```
//Before
resolvers: Inject(FooProvider)(fooProvider =>
//After
resolvers: InjectFunction(FooProvider)(fooProvider =>
```
> Implement to use Inject in a property with a breaking change

- package.json
- packages/core/package.json
- packages/di/package.json
- packages/epoxy/package.json
- packages/sonar/package.json
- packages/utils/package.json
I have the following function defined in my local shell:
```
npoh () {
open $(npm view $1 homepage)
}
```
I use that often for viewing documentation. When I ran `npoh @graphql-modules/core` the `open` command failed because there was no homepage entry in `package.json`.
Beyond my particular use case there is no link to the homepage or the repository from npm which made tracking down this repository more difficult than it should have been.
> chore: add homepage and repository entries for all packages

- docs/introduction/implement-your-providers.md
1. `_id` is of type ID which should be a string, else `Array.prototype.find` will not able to find it.
2. There are invalid codes behind the `injector` function chain.
> Fix documentation code bug

- packages/core/package.json
- packages/core/tsconfig.es2015.json
- packages/di/package.json
- packages/di/tsconfig.es2015.json
- packages/graphql-modules/package.json
- packages/graphql-modules/tsconfig.es2015.json
* Add `es2015` bundle
* Change target to `es2018` because NodeJS already supports `es2018`, no need to transpile code.
* Use `tslib` to reduce the code
> Support es2015 tree shaking

- docs/guides/data-sources.md
- packages/core/package.json
- packages/core/src/graphql-module.ts
- packages/core/src/module-session-info.ts
- packages/core/src/types.ts
- packages/core/tests/graphql-module.spec.ts
- packages/di/package.json
- packages/di/src/injector.ts
- yarn.lock
* Able to use DataSources without Session Scope
* `initialize` is no more a hook, so `initialize` is only called immediately after the instantitation of the provider
* Use Apollo's LRU Cache mechanism to prevent high memory usage for default GQL Modules mechanism
> Enhancements for DataSources

- packages/core/src/graphql-module.ts
- packages/core/tests/graphql-module.spec.ts
- packages/di/src/injector.ts
* Do not use promise as the return value of promise 
* Clone sessionProviders into Session Injector to prevent duplication of ModuleSessionInfo
> Fixes for memory usage

- docs/recipes/data-loader.md
I suppose `MY_DATA_LOADER` is supposed to be `USER_DATA_LOADER`. I might have misunderstood though, in which case you can ignore and close this PR.
> Fix typo in data-loader documentation

- docs/recipes/data-sources.md
Updating "Fetch External Data Using Data Sources" under "Recipes" in docs to include `ProviderScope.Session` in the example and some context for why we would choose to use it.
The existing example sent me on quite a long search to understand why data was being cached on a server that I'd implemented `apollo-datasource-rest` with GraphQL Modules. It's non-obvious to someone not familiarised with Provider Scopes in Dependency Injection. Hopefully the recommendation can save others confusing this.
Relates to apollographql/apollo-server#1765 and apollographql/apollo-server#2089
> Recommending ProviderScope.Session for REST Data Sources

- packages/core/src/graphql-module.ts
the cache is always reset to default on subsequent get after getting it the first time
(expect the same issue on selfLogger)
> selfCache getter overwriting with default when already defined issue

- docs/recipes/development-environment.md
Small fix in environment docs.
Per [https://github.com/TypeStrong/ts-node/issues/537](https://github.com/TypeStrong/ts-node/issues/537) the way of being able to run inspector is `-r ts-node/register`. I hit this issue while trying to debug in vscode
Hope it helps! cheers!
> Replace debug script according to ts-node docs

- packages/core/tests/graphql-module.spec.ts
- packages/di/src/injector.ts
When using token-injection based session providers with hooks I was running into an error:
```
GraphQL-Modules Error: Dependency Provider Not Found!
- Provider #_AuthProvider not provided in #Module AUTH_MODULE _SESSION scope!
Possible solutions:
- Check if you have this provider in your module.
- Check if you have the module of this provider imported in your dependent modules.
```
After digging deeper this appeared to be an issue with how there was a difference in how the provider was identified between `_hookServiceIdentifiersMap` and `_sessionScopeInstanceMap`. The hooks map was using the class that was passed as the `useClass` option whereas the session scope map was using the `provide` option.
This changes the way the hooks map identifies the provider so that it uses the `provide` …
> Fix issue with hook provider resolution when using custom provide option

- docs/introduction/resolvers-composition.md
This PR provides an example of `resolversComposition` using wild cards. 
given the issue https://github.com/Urigo/graphql-modules/issues/1015 I've decided to extend the example given on `resolversComposition` to surface wild-cards as an option. 
This is nothing new, but the documentation doesn't hint that the feature exists, and we can only know this when digging into [graphlq-toolkit repo](https://github.com/ardatan/graphql-toolkit/blob/master/packages/common/src/resolvers-composition.ts#L41-L72). I think it's a great feature and simplifies a lot the use of `resolversComposition` on GraphQL Modules
> Adding wild cards example to resolvers composition docs

- docs/recipes/schema-directives.md
- packages/core/src/graphql-module.ts
- packages/core/tests/graphql-module.spec.ts
- website/sidebars.json
Addresses #1086. Adds a `visitSchemaDirectives` option and documents schema directive usage.
> Add visitSchemaDirectives option

- package.json
- packages/core/src/graphql-module.ts
- packages/core/src/module-session-info.ts
- packages/core/tests/graphql-module.spec.ts
- packages/di/src/injectable.ts
- packages/di/src/injector.ts
- packages/di/src/types.ts
- packages/di/src/utils.ts
- packages/di/tests/di.spec.ts
The project already included husky and lint-staged. This just adds the pre-commit hook to actually run it. `typescript` had to be added to `devDependencies` to enable the `tslint` check. I also ran prettier to fix all the existing formatting issues in the codebase.
Note that `yarn rebuild` will need to be ran locally to actually install the hook per [the docs](https://github.com/typicode/husky#reinstall).
> Add pre-commit hook

- packages/graphql-modules/src/application/application.ts
- packages/graphql-modules/src/application/types.ts
- packages/graphql-modules/tests/index.spec.ts
A benign example:
```
const { injector } = createApplication(...)
server.listen({ port }, () => {
const logger = injector.get(Logger)
logger.info(`server ready at http://localhost:${port} 🚀`)
})
```
I ultimately use it for other things, but you get the idea. Cheers!
> Allow access to the app/singleton injector

- packages/graphql-modules/tests/subscription.spec.ts
Not sure how I think about it, but let's say we agreed on this one and have a confirmation in an integration test. Later on we can always change it.
> Operation provider should be instantiated on every subscription

- .changeset/twelve-flies-care.md
- packages/graphql-modules/src/application/apollo.ts
- packages/graphql-modules/src/application/application.ts
- packages/graphql-modules/src/application/context.ts
- packages/graphql-modules/src/application/execution.ts
- packages/graphql-modules/src/application/operation-controller.ts
- packages/graphql-modules/src/application/subscription.ts
- packages/graphql-modules/src/application/types.ts
- packages/graphql-modules/src/testing/graphql.ts
- packages/graphql-modules/src/testing/test-application.ts
- packages/graphql-modules/tests/operation-controller.spec.ts
The entire flow of GraphQL operation is being handled by `execute` or `subscribe` function that GraphQL Modules provides. That's the default and controlling those phases makes sure GM cleans everything after each request. In v0 this flow was dependent on `request` and `response` object which was causing many issues (memory leaks, awkward handling of subscriptions).
This PR introduces a new API. The object called `OperationController` is now responsible for managing the flow of GraphQL operation. The `OperationController` enables developer to access Operation-Scoped Injector (of application) before GraphQL Execution or Subscription begins and it's possible to access the Injector even after it happens.
A very important thing to understand is: you own the operation flow, so you're in charge …
> Manual control of GraphQL operation

- algolia/config.json
- website/patches/@docusaurus+theme-search-algolia+2.0.0-alpha.69.patch
- Adds Codegen to the list of websites to be indexed by docsearch
- Fixes bug with enterkey in search which led to routing within the same site
> Fixed bugs with Docsearch

- website/docs/get-started.md
The `typeDef` requires a `DocumentNode`, not a string:
Fixes  https://github.com/Urigo/graphql-modules/issues/1636
> Adjust the documentation to comply to the implementation

- .github/labels.yml
- .github/workflows/github.yml
@Urigo was looking to standardize the labels used in all the repos across The Guild to enable easier management. This PR is for the same.
- All labels are declared declaratively now with the help of this action to sync the same: https://github.com/micnncim/action-label-syncer
- Master Labels for all the repos are managed in this repo: https://github.com/the-guild-org/shared-resources and are pushed to all the repos using PAT whenever changes are made there
- Repo specific labels are added to the repo with an action to help them sync
**NOTE:** This does not remove any of the existing labels or changes the labels in the existing issues to avoid any trouble. It just adds new ones. Relabelling of issues would be required in the future
This is how …
> Added Github action for Declarative label declaration, Standard Labels added for The Guild

- website/docs/di/introduction.md
Updating docs to better guide babel users to use the DI section of GraphQL Modules
> docs: Adding a link to the ts metadata plugin for babel

- packages/graphql-modules/src/application/apollo.ts
Based on debugging the issue, it appears that while we delete session on end of each mutation, we do not delete the corresponding context key. In the beginning of the next mutation, the session looks for the context key and crashes with `undefined` .
While I'm not 100% sure that it is the right idea to delete the key or even the session on the end of every mutation, this fixes the visible problem. It might be better if they could share the same session (I believe that is what we have the count for). Such a fix, however, would be a bigger design change and beyond my skills with this module.
Fixes #1732  
Ran the automated tests but I did not create a new one to verify the fix & issue. If this is needed to get the MR accepted, I'll try to get …
> Fixes 1732: Fix the failure of missing session when multi-mutation operation

- website/docs/recipes/migration.md
Fix a typo'd `createModule` property in the migration doco.
> Fix typo in migration doco

- README.md
- packages/graphql-modules/CHANGELOG.md
- website/docusaurus.config.js
- website/src/ui/home/contact-us.js
- website/src/ui/home/intro.js
Regression since commit: ecd49ba442335c6941aa3a4bfffed6930981b79a
Most likely the new major of Docusaurus has a less permissive routing.
----
> [deploy_website] fix(nav): broken documentation link since the update to docusaurus@2 beta

- examples/apollo-subscriptions/src/app/index.ts
- examples/apollo-subscriptions/src/index.ts
- examples/subscriptions/src/app/index.ts
- examples/subscriptions/src/index.ts
- package.json
- website/docs/api.mdx
- website/docs/get-started.mdx
- yarn.lock
GraphQL Modules need to control execution lifecycle so it generates custom execute and subscribe functions instead of graphql-js’s default ones.
Unfortunately Apollo Server doesn’t support custom execute and subscribe functions but instead you can provide executor function that does similar job but it doesn’t support subscriptions. We have introduced createApolloExecutor but it wasn’t enough for Apollo users that also use subscriptions. So we decided to use @graphql-tools/wrap which allows you to create a standalone schema with custom execution logic just like we need for GraphQL Modules. But it has some performance downsides.
After Apollo Server v3, they dropped builtin subscriptions implementation. Then I realized we don’t need to create wrapped schemas from now on.
_Side not about …
> Replace createSchemaForApollo with createApolloExecutor in docs

- .changeset/wet-peaches-yell.md
- .github/workflows/algolia-integrity.yml
- .github/workflows/algolia-publish.yml
- .github/workflows/benchmark.yml
- .github/workflows/canary.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- jest.config.base.js
- packages/graphql-modules/src/application/context.ts
- packages/graphql-modules/src/application/execution-context.ts
- packages/graphql-modules/tests/di-providers.spec.ts
- packages/graphql-modules/tests/execution-context.spec.ts
- packages/graphql-modules/tests/federation.spec.ts
> Fix a memory leak related to ExecutionContext and Promises

- .changeset/tough-papayas-hammer.md
- packages/graphql-modules/package.json
Related to #2323 
[Typescript 5.0 is in beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler), and it adds a couple new compiler options.
If you want to use the new moduleResolution mode "bundler" or compiler option "resolvePackageJsonExports", Typescript will ignore the top-level "types" field in your package.json and only look for types inside package.json "exports".
See: https://github.com/microsoft/TypeScript/issues/52363
That means, types need to be directly pointed at in package.json exports.
Partially addresses #2323 
> Update package json exports to include type definitions

- .changeset/lazy-bulldogs-cry.md
- packages/graphql-modules/src/di/decorators.ts
Typescript 5 has [tighter parameter decorator checking with --experimentalDecorators](https://github.com/microsoft/TypeScript/issues/52435).
That means [constructor parameter decorators should allow undefined as the type of key](https://github.com/nestjs/nest/issues/10959).
Fixes [# (issue)](https://github.com/Urigo/graphql-modules/issues/2328)
I've tested patched graphql-modules in a project that makes use of TS5 and the `Inject` decorator.
- OS: Gentoo Linux ppc64le
- `graphql-modules`: 2.1.1
- NodeJS: v18.15.0
> fix: inject and optional decorators should allow key to be undefined

- .changeset/hip-elephants-warn.md
- packages/graphql-modules/src/application/execution-context-async-local-storage.ts
- packages/graphql-modules/src/application/execution-context-hooks.ts
- packages/graphql-modules/src/application/execution-context.interface.ts
- packages/graphql-modules/src/application/execution-context.ts
- packages/graphql-modules/tests/execution-context.spec.ts
- OS:
- `@graphql-modules/...`:
- …
> Use AsyncLocalStorage for execution context if available

- .changeset/perfect-lamps-cheat.md
- packages/graphql-modules/src/di/injector.ts
- packages/graphql-modules/src/di/providers.ts
Support passing an abstract class to `Injector.get` call and `Provider` value.
> feat: allow providing abstract type

- .changeset/nice-eels-press.md
- packages/graphql-modules/src/module/resolvers.ts
- packages/graphql-modules/tests/bootstrap.spec.ts
- website/src/content/essentials/resolvers.mdx
This change makes it possible to use graphql-modules with resolver extensions such as grafast, graphql-query-complexity and others.
Fixes #2615
- OS: masOS 15.5
- `@graphql-modules/...`: 3.0.0
- NodeJS: v24.3.0
This is a pretty trivial change, but will significantly improve compatibility of graphql-modules with the rest of graphql ecosystem.
> Enables support for resolver extensions for compatibility with grafast, complexity, etc.
